# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 02:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20160611_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='put_date',
            new_name='pub_date',
        ),
    ]
